/**
 * Single authoritative registry of every Electron IPC channel used across
 * main/preload (registration, invocation, push events). Guarded by
 * src/shared/ipcChannels.test.ts, which scans main and preload sources and
 * fails on any unregistered channel literal (and on registered channels
 * nothing uses). Mechanical call-site adoption of these constants is a
 * follow-up; the registry plus the drift guard is the source of truth.
 */
export const IPC_CHANNELS = {
  chatSendMessage: "chat:sendMessage",
  chatCancelMessage: "chat:cancelMessage",
  chatRespondSkillInput: "chat:respondSkillInput",
  chatStatusEvent: "chat:statusEvent",
  chatStreamEvent: "chat:streamEvent",
} as const;

export const ALL_IPC_CHANNELS = {
  agentBootstrapLoadValidation: "agentBootstrap:loadValidation",
  agentBootstrapPrepare: "agentBootstrap:prepare",
  agentBootstrapValidate: "agentBootstrap:validate",
  agentEvalCandidatesAccept: "agentEvalCandidates:accept",
  agentEvalCandidatesGenerateForRun: "agentEvalCandidates:generateForRun",
  agentEvalCandidatesList: "agentEvalCandidates:list",
  agentEvalCandidatesPromote: "agentEvalCandidates:promote",
  agentEvalCandidatesReject: "agentEvalCandidates:reject",
  agentQualityGetEvalReport: "agentQuality:getEvalReport",
  agentRunsCancelTask: "agentRuns:cancelTask",
  agentRunsChanged: "agentRuns:changed",
  agentRunsGetTrajectoryPage: "agentRuns:getTrajectoryPage",
  agentRunsList: "agentRuns:list",
  agentRunsListActiveExecutions: "agentRuns:listActiveExecutions",
  agentRunsListTrajectory: "agentRuns:listTrajectory",
  agentRunsOpenSession: "agentRuns:openSession",
  agentRunsPause: "agentRuns:pause",
  agentRunsResume: "agentRuns:resume",
  agentRunsRetry: "agentRuns:retry",
  agentRunsRunTask: "agentRuns:runTask",
  agentRunsRunTaskStreaming: "agentRuns:runTaskStreaming",
  agentStreamEvent: "agent:streamEvent",
  agentWorkspacesCreateTemporary: "agentWorkspaces:createTemporary",
  agentWorkspacesList: "agentWorkspaces:list",
  agentWorkspacesOpenProject: "agentWorkspaces:openProject",
  agentWorkspacesRequestGitWorktree: "agentWorkspaces:requestGitWorktree",
  appCheckForUpdates: "app:checkForUpdates",
  appGetMeta: "app:getMeta",
  appGetRuntimeInfo: "app:getRuntimeInfo",
  appGetUpdateState: "app:getUpdateState",
  appInstallUpdate: "app:installUpdate",
  appUpdateStateChanged: "app:updateStateChanged",
  chatSessionsArchive: "chatSessions:archive",
  chatSessionsDelete: "chatSessions:delete",
  chatSessionsGet: "chatSessions:get",
  chatSessionsGetTranscriptPage: "chatSessions:getTranscriptPage",
  chatSessionsList: "chatSessions:list",
  chatSessionsRename: "chatSessions:rename",
  chatSessionsRestore: "chatSessions:restore",
  goalCancel: "goal:cancel",
  goalContinueAcceptance: "goal:continueAcceptance",
  goalCreate: "goal:create",
  goalDraftConfirm: "goalDraft:confirm",
  goalDraftDiscard: "goalDraft:discard",
  goalGet: "goal:get",
  goalListActive: "goal:listActive",
  goalMarkCompletedUnverified: "goal:markCompletedUnverified",
  goalMilestoneRunEvent: "goal:milestoneRunEvent",
  goalPause: "goal:pause",
  goalProgressEvent: "goal:progressEvent",
  goalProposeAmendment: "goal:proposeAmendment",
  goalReplan: "goal:replan",
  goalResolveReview: "goal:resolveReview",
  goalResume: "goal:resume",
  goalRetry: "goal:retry",
  goalStart: "goal:start",
  historyAround: "history:around",
  historySearch: "history:search",
  learningAcceptCandidate: "learning:acceptCandidate",
  learningApplyAccepted: "learning:applyAccepted",
  learningListCandidates: "learning:listCandidates",
  learningRejectCandidate: "learning:rejectCandidate",
  memoryAcceptIngestionCandidate: "memory:acceptIngestionCandidate",
  memoryCreate: "memory:create",
  memoryDelete: "memory:delete",
  memoryEvaluate: "memory:evaluate",
  memoryExport: "memory:export",
  memoryGetIngestionStatus: "memory:getIngestionStatus",
  memoryGovernance: "memory:governance",
  memoryIngestRecent: "memory:ingestRecent",
  memoryList: "memory:list",
  memoryListIngestionCandidates: "memory:listIngestionCandidates",
  memoryMaintain: "memory:maintain",
  memoryProfileRead: "memoryProfile:read",
  memoryProfileSave: "memoryProfile:save",
  memoryRejectIngestionCandidate: "memory:rejectIngestionCandidate",
  memorySearch: "memory:search",
  modelCatalogDeleteConnection: "modelCatalog:deleteConnection",
  modelCatalogDeleteProfile: "modelCatalog:deleteProfile",
  modelCatalogLoad: "modelCatalog:load",
  modelCatalogSaveConnection: "modelCatalog:saveConnection",
  modelCatalogSaveProfile: "modelCatalog:saveProfile",
  modelCatalogSetModelHidden: "modelCatalog:setModelHidden",
  modelCatalogTestAndSaveConnection: "modelCatalog:testAndSaveConnection",
  modelCatalogTestProvider: "modelCatalog:testProvider",
  modelSettingsLoad: "modelSettings:load",
  modelSettingsSave: "modelSettings:save",
  modelSettingsTestConnection: "modelSettings:testConnection",
  multiAgentSessionsList: "multiAgentSessions:list",
  navigationList: "navigation:list",
  plansAdoptGoalPlan: "plans:adoptGoalPlan",
  plansConfirm: "plans:confirm",
  plansDiscard: "plans:discard",
  plansGet: "plans:get",
  plansGetLatestBySession: "plans:getLatestBySession",
  scheduledTasksCreate: "scheduledTasks:create",
  scheduledTasksDelete: "scheduledTasks:delete",
  scheduledTasksList: "scheduledTasks:list",
  scheduledTasksSetEnabled: "scheduledTasks:setEnabled",
  scheduledTasksUpdate: "scheduledTasks:update",
  skillsList: "skills:list",
  toolApprovalDecision: "toolApproval:decision",
  toolApprovalGetMode: "toolApproval:getMode",
  toolApprovalListPending: "toolApproval:listPending",
  toolApprovalModeChanged: "toolApproval:modeChanged",
  toolApprovalRequest: "toolApproval:request",
  toolApprovalResolve: "toolApproval:resolve",
  toolApprovalSetAutoApprovalEnabled: "toolApproval:setAutoApprovalEnabled",
  toolApprovalSetGoalModeEnabled: "toolApproval:setGoalModeEnabled",
  toolApprovalSetPolicyDenyOverrideEnabled: "toolApproval:setPolicyDenyOverrideEnabled",
  toolAuditList: "toolAudit:list",
  toolPermissionsAuthorize: "toolPermissions:authorize",
  toolResultsReadRef: "toolResults:readRef",
} as const;
